/**
 * Freecat-Blog 构建编排器
 *
 * 整体流程：
 *   1. 清理 dist 并搬运 assets / image
 *   2. 加载站点 / 社交 / 关于页面三份配置（Control/*.md）
 *   3. 准备模板引擎（注入 partials + tailwind config + SITE_*）
 *   4. 依次生成：post 详情页 → 分页首页 → all.html → search.html + 索引 → about.html → sitemap/robots
 *
 * 各步骤的实际逻辑都拆在 build/*.js 中，本文件仅做编排。
 */

const fs = require('fs');
const path = require('path');
const dayjs = require('dayjs');
const utc = require('dayjs/plugin/utc');
const timezone = require('dayjs/plugin/timezone');

dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault('Asia/Shanghai');

const gitDatesModule = require('./build/git-dates.js');
const { loadConfig } = require('./build/config.js');
const { SOCIAL_DEFAULTS } = require('./build/social-defaults.js');
const { createEngine } = require('./build/template-engine.js');
const { copyDir, ensureCleanDir } = require('./build/fs-utils.js');
const { buildTailwindCss } = require('./build/tailwind.js');
const { minifyDist } = require('./build/minify.js');
const postPage = require('./build/pages/post.js');
const indexPage = require('./build/pages/index.js');
const allPage = require('./build/pages/all.js');
const searchPage = require('./build/pages/search.js');
const aboutPage = require('./build/pages/about.js');
const { generateSitemap, generateRobotsTxt, generateLlmsTxt, generateFeed } = require('./build/pages/sitemap.js');

// ===== 路径常量 =====
const DEFAULT_POSTS_PER_PAGE = 8;
const DEFAULT_RECENT_POSTS_LIMIT = 7;
const DIRS = {
    posts: path.join(__dirname, '..', 'writing'),
    assets: path.join(__dirname, 'src', 'assets'),
    images: path.join(__dirname, 'image'),
    output: path.join(__dirname, 'dist'),
    templates: path.join(__dirname, 'src'),
    partials: path.join(__dirname, 'src', 'partials'),
    control: path.join(__dirname, '..', 'Control')
};

// ===== 1. 清理输出目录 + 搬运静态资源 =====
ensureCleanDir(DIRS.output);
fs.mkdirSync(path.join(DIRS.output, 'posts'));

console.log('📦 Moving assets and configs...');
if (fs.existsSync(DIRS.assets)) copyDir(DIRS.assets, path.join(DIRS.output, 'assets'));
if (fs.existsSync(DIRS.images)) copyDir(DIRS.images, path.join(DIRS.output, 'image'));

// ===== 2. 加载 git dates =====
// Production builds must use the committed snapshot generated by GitHub Actions.
// Do not fall back to file mtimes here; checkout mtimes are not article edit times.
const gitDates = gitDatesModule.loadSnapshot({
    snapshotPath: path.join(__dirname, 'git-dates.json'),
    required: true
});

// ===== 3. 加载配置（site / social / about） =====
console.log('⚙️ Loading site configuration...');
const siteDefaults = {
    site_title: 'FreeCat Blog',
    site_name: 'FreeCat',
    footer_copyright: '© FreeCat | Curiosity is the best motivation.',
    hero_title: 'Hi, I\'m FreeCat.Building Blog & writing.',
    hero_subtitle: 'Always maintain a strong curiosity and be willing to explore a world of freedom, experiencing a life of liberty.',
    hero_avatar: '/image/freecat.png',
    posts_per_page: DEFAULT_POSTS_PER_PAGE,
    default_theme: 'system',
    site_logo_icon: '',
    site_favicon: '/image/freecat_web_icon.png',
    site_url: '',
    show_recent_posts: false
};
const siteConfig = loadConfig(DIRS.control, 'site', 'site.md', siteDefaults);
if (!siteConfig.site_favicon) siteConfig.site_favicon = '/image/freecat_web_icon.png';
if (!siteConfig.hero_avatar) siteConfig.hero_avatar = '/image/freecat.png';

const rawPostsPerPage = siteConfig.posts_per_page;
const parsedPostsPerPage = rawPostsPerPage === '' || rawPostsPerPage == null
    ? Number.NaN
    : Number(rawPostsPerPage);
const POSTS_PER_PAGE = Number.isFinite(parsedPostsPerPage) && parsedPostsPerPage >= 0
    ? Math.floor(parsedPostsPerPage)
    : DEFAULT_POSTS_PER_PAGE;
const ASSET_VERSION = process.env.CF_PAGES_COMMIT_SHA || process.env.COMMIT_SHA || String(Date.now());

console.log('📱 Loading social media configuration...');
const socialConfig = loadConfig(DIRS.control, 'social', 'social.md', SOCIAL_DEFAULTS);

console.log('🔎 Loading SEO configuration...');
const seoConfig = loadConfig(DIRS.control, 'SEO', 'SEO_搜索优化.md', {
    site_url: '',
    site_description: '',
    site_language: 'zh-CN',
    site_author: '',
    site_author_url: '',
    site_default_image: '',
    allow_ai_crawlers: true,
    enable_llms_txt: true
});
if (seoConfig.site_url) siteConfig.site_url = seoConfig.site_url;

console.log('👤 Loading about page configuration...');
const aboutConfig = loadConfig(DIRS.control, 'about', 'about.md', {
    about_hero_title: '',
    about_hero_subtitle: '',
    about_hero_avatar: '/image/freecat.png'
});

// ===== 4. 模板引擎 =====
const engine = createEngine({
    templatesDir: DIRS.templates,
    partialsDir: DIRS.partials,
    siteConfig,
    seoConfig,
    socialConfig,
    assetVersion: ASSET_VERSION
});

const tplIndex = engine.loadTemplate('template_index.html');
const tplPost = engine.loadTemplate('template_post.html');
const tplIndexAll = engine.loadTemplate('template_index_all.html');
const tplSearch = engine.loadTemplate('template_index_search.html');
const tplAbout = engine.loadTemplate('template_index_About.html');

// ===== 5. 加载并排序文章 =====
console.log('📝 Processing posts...');
const allPosts = postPage.loadPosts({ postsDir: DIRS.posts, gitDates });

// ===== 5.5 生成最近更新文章列表 HTML =====
let recentPostsSidebarWrapperHtml = '';
let recentPostsSidebarHomeWrapperHtml = '';
let recentPostsSidebarAllWrapperHtml = '';
let recentPostsSidebarInnerHtml = '';

if (siteConfig.show_recent_posts === true) {
    const recentPosts = [...allPosts]
        .sort((a, b) => b.modifiedDate.valueOf() - a.modifiedDate.valueOf())
        .slice(0, DEFAULT_RECENT_POSTS_LIMIT);

    const itemsHtml = recentPosts.map(post => {
        const safeTitle = engine.shared.escapeHtml(post.title);
        const safeLink = engine.shared.escapeHtml(post.link);
        return `
                            <li class="py-3">
                                <a href="${safeLink}" class="block text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors duration-150 line-clamp-2">
                                    ${safeTitle}
                                </a>
                            </li>`;
    }).join('\n');

    recentPostsSidebarInnerHtml = `
                        <div class="flex flex-col flex-shrink-0 mt-8">
                            <h3 class="text-sm font-semibold tracking-wider text-slate-600 dark:text-slate-300 mb-4">
                                最近更新
                            </h3>
                            <ul class="flex flex-col divide-y divide-slate-200 dark:divide-slate-700">
                                ${itemsHtml.trim()}
                            </ul>
                        </div>`;

    recentPostsSidebarWrapperHtml = `
                    <aside class="hidden lg:block sticky top-32 w-64 flex-shrink-0 self-start">
                        ${recentPostsSidebarInnerHtml.trim()}
                    </aside>`;

    recentPostsSidebarHomeWrapperHtml = `
                    <aside id="home-recent-posts-shell" class="freecat-home-recent-shell absolute top-0 w-64" style="margin-top: calc(var(--freecat-posts-gap) + 36px); left: min(calc(100% - 16rem), calc(50% + 720px));">
                        <div id="home-recent-posts-sidebar" class="freecat-home-recent-sidebar max-h-[calc(100vh-10rem)] overflow-y-auto pr-1 custom-scrollbar">
                            ${recentPostsSidebarInnerHtml.replace(' mt-8', '').trim()}
                        </div>
                    </aside>`;

    recentPostsSidebarAllWrapperHtml = `
                    <aside id="home-recent-posts-shell" class="freecat-home-recent-shell absolute top-0 w-64" style="left: calc(100% + 96px);">
                        <div id="home-recent-posts-sidebar" class="freecat-home-recent-sidebar max-h-[calc(100vh-10rem)] overflow-y-auto pr-1 custom-scrollbar">
                            ${recentPostsSidebarInnerHtml.replace(' mt-8', '').trim()}
                        </div>
                    </aside>`;
}

// ===== 6. 生成各页面 =====
postPage.generateAll({ posts: allPosts, template: tplPost, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarInnerHtml });
indexPage.generateAll({ posts: allPosts, template: tplIndex, postsPerPage: POSTS_PER_PAGE, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarHomeWrapperHtml });
allPage.generate({ posts: allPosts, template: tplIndexAll, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarAllWrapperHtml });
searchPage.generate({ posts: allPosts, template: tplSearch, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarAllWrapperHtml });
aboutPage.generate({ template: tplAbout, siteConfig, seoConfig, aboutConfig, outputDir: DIRS.output });
generateSitemap({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });
generateRobotsTxt({ siteConfig, seoConfig, outputDir: DIRS.output });
generateLlmsTxt({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });
generateFeed({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });

// ===== 7. 复制部署平台配置 (_headers / vercel.json) =====
const deployConfigs = ['_headers', 'vercel.json'];
for (const name of deployConfigs) {
    const src = path.join(DIRS.templates, name);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(DIRS.output, name));
}

// ===== 8. 编译 Tailwind（必须最后做，扫描的是已生成的 dist HTML + 拼装 HTML 字符串的 build/ JS） =====
console.log('🎨 Compiling Tailwind CSS...');
buildTailwindCss({
    contentGlobs: [
        path.join(DIRS.output, '**/*.html'),
        path.join(DIRS.assets, '**/*.{html,js,css}'),
        path.join(__dirname, 'build', '**/*.js')
    ],
    outputPath: path.join(DIRS.output, 'assets', 'tailwind.css'),
    minify: true
}).then(async ({ size }) => {
    const sizeKb = (size / 1024).toFixed(1);
    console.log(`   tailwind.css: ${sizeKb} KB`);

    // ===== 9. Minify HTML / JS（必须在 Tailwind 之后，因为 Tailwind 会扫描已生成的 HTML） =====
    if (process.env.NO_MINIFY !== '1') {
        console.log('🗜️  Minifying HTML & JS...');
        await minifyDist(DIRS.output);
    }

    console.log('🚀 Build Complete: Posts & Index pages generated!');
}).catch(err => {
    console.error('❌ Build failed:', err);
    process.exit(1);
});
